routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@welcome');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('lot', 'LotController')->middleware('auth');
Route::resource('sales', 'SalesController')->middleware('auth');
Route::resource('purchase', 'PurchaseController')->middleware('auth');
Route::resource('purchaseReturn', 'PurchaseReturnController')->middleware('auth');
Route::resource('salesReturn', 'SalesReturnController')->middleware('auth');
Route::resource('investor', 'InvestorController')->middleware('auth');
Route::resource('expenses', 'ExpensesController')->middleware('auth');
Route::post('/vendors/store', 'VendorController@store');
Route::post('/customers/store', 'CustomerController@store');
Route::get('profitLoss', 'HomeController@profitLoss')->middleware('auth');
Route::get('stocks', 'HomeController@stock')->middleware('auth');
Route::fallback('PageController@error');

app/Sales.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sales extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'model_no', 'customer_id', 'bill_no', 'quantity', 'price', 'sales_date', 'mode',
    ];
}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\Sales;
use App\Stock;
use App\Customer;
use App\Services\StockMaintainer;

use Illuminate\Http\Request;

class SalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $stockMaintain;

    public function __construct(StockMaintainer $stockMaintain)
    {
        $this->stockMaintain = $stockMaintain;
    }

    public function index()
    {
        $lot = session()->get('lot');
        $sales = Sales::all();
        $customers = Customer::all();
        return view('backend.sales.index', compact('sales', 'lot', 'customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lot = session()->get('lot');
        $stocks = Stock::where('stock', '>=', 1)->get();
        $customers = Customer::all();
        return view('backend.sales.create', compact('lot', 'stocks', 'customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $stocker = $this->stockMaintain->stockMaintainOnSales($request->model_no, $request->quantity);
        if ($stocker) {
            $sales = Sales::create($request->all());
            if ($sales->wasRecentlyCreated) {
                return redirect('/sales')->with('success', 'New sales record is entered!');
            }
            return redirect('/sales')->with('error', 'Error on entering sale record.');
        }
        return redirect('/sales')->with('error', 'Out of Stock!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sales  $sales
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sales  $sales
     * @return \Illuminate\Http\Response
     */
    public function edit(Sales $sale)
    {
        $customers = Customer::all();
        $stocks = Stock::all();
        return view('backend.sales.edit', compact('sale', 'stocks', 'customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sales  $sales
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sales $sale)
    {
        if ($sale->quantity > $request->quantity) {
            $stocker = $this->stockMaintain->stockMaintainOnPurchase($sale->model_no, $sale->quantity - $request->quantity);
            if ($stocker) {
                $this->updateSalesRecord($sale, $request);
            }
            return redirect('/sales')->with('error', 'Error on sales record update.');
        } elseif ($sale->quantity < $request->quantity) {
            $stocker = $this->stockMaintain->stockMaintainOnSales($sale->model_no, $request->quantity - $sale->quantity);
            if ($stocker) {
                $this->updateSalesRecord($sale, $request);
            }
            return
                redirect('/sales')->with('error', 'Error on sales record update.');
        } else {
            $this->updateSalesRecord($sale, $request);
        }
        return redirect('/sales')->with('error', 'Error on sales record update.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sales  $sales
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sales $sale)
    {
        $stocker =
            $this->stockMaintain->stockMaintainOnPurchase($sale->model_no, $sale->quantity);
        if ($stocker) {
            $sale->delete();
            return redirect('/sales')->with('success', 'An sales record has been deleted successfully!');
        }
        return redirect('/sales')->with('error', 'Error on sales record delete.');
    }

    public function updateSalesRecord($sale, $request)
    {
        $sale->update($request->all());
        return redirect('/sales')->with('success', 'An existing sales record has been updated!');
    }
}

resources/views/backend/sales/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            @if(count($stocks))
            <div class="card-header">
                <h4 class="card-title">Add New Sales Record</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('sales.store') }}" method="POST" class="addForm" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group col-md-4">
                        <label for="model_no">Model Number</label>
                        <select name="model_no" id="modelNo" class="form-control" required
                            onchange="limitQuantity({{ $stocks }})">
                            <option value="">Select the Model No</option>
                            @foreach($stocks as $stock)
                            <option value="{{ $stock->model_no }}">{{ $stock->model_no }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="quantity">Quantity</label>
                        <input type="number" name="quantity" class="form-control" id="quantity" min="1" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="bill_no">Bill Number</label>
                        <input type="text" name="bill_no" class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="price">Price</label>
                        <input type="text" name="price" class="form-control" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="mode">Mode of Payment</label>
                        <select name="mode" id="" class="form-control" required>
                            <option value="0">Cash</option>
                            <option value="1">Credit</option>
                        </select>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="sales_date">Sales Date</label>
                        <input type="date" name="sales_date" class="form-control" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="customer_id">Customer</label>
                        <select name="customer_id" id="customerSelect" class="form-control">
                            <option value="">Select the Customer</option>
                            @foreach($customers as $customer)
                            <option value="{{ $customer->id }}">{{ $customer->customer }}</option>
                            @endforeach
                        </select>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addCustomer">
                            Didn't find Customer?
                        </button>
                    </div>
                    <button type="submit" class="btn btn-block col-md-4">Submit</button>
                </form>
            </div>
            @else
            <div class="card-header">
                <h4 class="card-title">Out of Stock, Please enter a purchase first</h4>
            </div>
            @endif
        </div>
    </div>
</div>

<div class="modal fade" id="addCustomer" tabindex="-1" role="dialog" aria-labelledby="addCustomerTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h5 class="modal-title" id="addCustomerTitle">Add a New Customer</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="company_name">Company Name</label>
                        </div>

                        <div class="col-sm-8">
                            <input type="text" name="company_name" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="PAN">PAN</label>
                        </div>

                        <div class="col-sm-8">
                            <input type="text" name="PAN" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="customer">Customer Name</label>
                        </div>

                        <div class="col-sm-8">
                            <input type="text" name="customer" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="location">Location</label>
                        </div>

                        <div class="col-sm-8">
                            <input type="text" name="location" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="customer_phone">Customer Phone</label>
                        </div>

                        <div class="col-sm-8">
                            <input type="text" name="customer_phone" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label for="points">Purchase Points</label>
                        </div>

                        <div class="col-sm-8">
                            <input type="text" name="points" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-submitcustomer">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
function limitQuantity(stocks) {
    var modelNo = $('#modelNo').val();
    stocks.forEach((stock) => {
        if (stock.model_no == modelNo) {
            if (stock.stock > 0) {
                $('#quantity').attr('max', stock.stock);
            } else {
                window.location.href = '/sales';
            }
        }
    });
}

$.ajaxSetup({

    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});



$(".btn-submitcustomer").click(function(e) {
    e.preventDefault();
    var company_name = $("input[name=company_name]").val();
    var PAN = $("input[name=PAN]").val();
    var customer = $("input[name=customer]").val();
    var location = $("input[name=location]").val();
    var customer_phone = $("input[name=customer_phone]").val();
    var points = $("input[name=points]").val();
    $.ajax({
        type: 'POST',
        url: '/customers/store',
        data: {
            company_name: company_name,
            PAN: PAN,
            customer: customer,
            location: location,
            customer_phone: customer_phone,
            points: points
        },
        success: function(data) {
            $('#addCustomer').modal('hide');
            $('#customerSelect').append(new Option(data[1]['customer'], data[1]['id']));
            console.log(data);
        },
        error: function(data, textStatus, errorThrown) {
            console.log(data);
        }
    });
});
</script>

@endsection

resources/views/backend/sales/index.blade.php
@extends('layouts.admin')

@section('styles')
<link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<style>
div#salesReturn .form-group {
    display: inline-block;
    margin: 5px 15px;
}

.red {
    background-color: red !important;
    color: white;
}

.red:after {
    content: 'Credit';
    position: absolute;
    left: -13px;
    color: black;
    background: white;
    padding: 3px 35px;
    transform: rotate(-36deg);
    margin-top: 10px;
}
</style>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    Sales Record
                </h4>
                <div>
                    <a href="{{ route('sales.create') }}" class="btn">
                        Add New Sales
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table datatable">
                        <thead class="text-primary">
                            <tr>
                                <th>
                                    S.N
                                </th>
                                <th>
                                    Model No
                                </th>
                                <th>
                                    Quantity
                                </th>
                                <th>
                                    Bill No.
                                </th>
                                <th>
                                    Customer Details
                                </th>
                                <th>
                                    Price
                                </th>
                                <th>
                                    Quantity
                                </th>
                                <th>
                                    Date
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($sales as $sales_record)
                            <tr class="{{ $sales_record->mode == 1 ? 'red' : '' }}">
                                <td>
                                    {{ $loop->iteration }}
                                </td>
                                <td>
                                    {{ $sales_record->model_no }}
                                </td>
                                <td>
                                    {{ $sales_record->quantity }}
                                </td>
                                <td>
                                    {{ $sales_record->bill_no }}
                                </td>
                                <td>
                                    @foreach($customers as $customer)
                                    @if($customer->id == $sales_record->customer_id)
                                    Company Name: {{ $customer->company_name }}<br>
                                    PAN: {{ $customer->PAN }}<br>
                                    Contact Person: {{ $customer->customer }}<br>
                                    Phone: {{ $customer->customer_phone }}<br>
                                    Location: {{ $customer->location }}
                                    @endif
                                    @endforeach
                                </td>
                                <td>
                                    {{ $sales_record->price }}
                                </td>
                                <td>
                                    {{ $sales_record->quantity }}
                                </td>
                                <td>
                                    {{ $sales_record->sales_date }}
                                </td>
                                <td>
                                    <a href="{{ route('sales.edit', $sales_record->id) }}"
                                        class="btn btn-success btn-block mb-1">Edit</a>

                                    <button type="button" class="btn btn-primary btn-block mb-1" data-toggle="modal"
                                        data-target="#salesReturn">
                                        Return ?
                                    </button>

                                    <div class="modal fade" id="salesReturn" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <form action="{{ route('salesReturn.store') }}" method="POST"
                                                enctype="multipart/form-data">
                                                @csrf
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="title">Sales Return</h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <input type="hidden" name="lot_id" value="{{ $lot->id }}">
                                                        <input type="hidden" name="sales_id"
                                                            value="{{ $sales_record->id }}">
                                                        <div class="form-group">
                                                            <label for="quantity">Quantity</label>
                                                            <input type="text" name="quantity" required
                                                                class="form-control">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="return_date">Return Date</label>
                                                            <input type="date" name="return_date" required
                                                                class="form-control">
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Save
                                                            changes</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    <form action="{{ route('sales.destroy', $sales_record->id) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-block"
                                            onclick="promtAlert(event)">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script>
function promtAlert(evt) {
    var ans = confirm('Are you sure to delete?');
    if (!ans) {
        evt.preventDefault();
        evt.stopPropagation();
    }
}
$(document).ready(function() {
    $('.datatable').DataTable();
});
</script>
@endsection