routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@welcome');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('lot', 'LotController')->middleware('auth');
Route::resource('sales', 'SalesController')->middleware('auth');
Route::resource('purchase', 'PurchaseController')->middleware('auth');
Route::resource('purchaseReturn', 'PurchaseReturnController')->middleware('auth');
Route::resource('salesReturn', 'SalesReturnController')->middleware('auth');
Route::resource('investor', 'InvestorController')->middleware('auth');
Route::resource('expenses', 'ExpensesController')->middleware('auth');
Route::post('/vendors/store', 'VendorController@store');
Route::post('/customers/store', 'CustomerController@store');
Route::get('profitLoss', 'HomeController@profitLoss')->middleware('auth');
Route::get('stocks', 'HomeController@stock')->middleware('auth');
Route::fallback('PageController@error');

resources/views/backend/dashboard.blade.php
@extends('layouts.admin')

@section('styles')
<link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<style>
.stock {
    border: 1px solid #efefef;
    text-align: center;
    padding: 9px 10px;
    box-shadow: 3px 3px 8px #c2c2c2c7;
    display: inline-block;
    background: #2ca8ff;
    color: white;
}
</style>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-4">
        <div class="card card-chart">
            <div class="card-header collapsible" data-toggle="collapse" data-target="#investment">
                <h5 class="text-center">Total Investments: <br><strong>{{ $totalInvestment }}</strong></h5>
            </div>
            <div class="card-body collapse collapse-panel" id="investment">
                @foreach($investors as $investment)
                <div class="row">
                    <div class="col-sm-6">
                        {{ $investment->name }}
                    </div>
                    <div class="col-sm-6">
                        {{ $investment->amount }}
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card card-chart">
            <div class="card-header collapsible" data-toggle="collapse" data-target="#expenseAmt">
                <h5 class="text-center">Total Expenses: <br><strong>{{ $totalExpenses }}</strong></h5>
            </div>
            <div class="card-body collapse collapse-panel" id="expenseAmt">
                @foreach($expenses as $expense)
                <div class="row">
                    <div class="col-sm-6">
                        {{ $expense->title }}
                    </div>
                    <div class="col-sm-6">
                        {{ $expense->amount }}
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card card-chart">
            <div class="card-header collapsible" data-toggle="collapse" data-target="#remainingAmt">
                <h5 class="text-center">Remaining Amount: <br><strong>{{ $remainingAmt }}</strong></h5>
            </div>
            <div class="card-body collapse collapse-panel" id="remainingAmt">
                <div class="row">
                    <div class="col-sm-8">
                        Cash in Hand
                    </div>
                    <div class="col-sm-4">
                        {{ $remainingAmt }}
                    </div>
                    <div class="col-sm-8">
                        Sundry Creditor
                    </div>
                    <div class="col-sm-4">
                        {{ $totalSalesArr['credit'] }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card card-chart">
            <div class="card-header collapsible" data-toggle="collapse" data-target="#salesAmt">
                <h5 class="text-center">Total Sales: <br><strong>{{ $totalSalesArr['sales'] }}</strong></h5>
            </div>
            <div class="card-body collapse collapse-panel" id="salesAmt">
                <div class="row">
                    <div class="col-sm-6">
                        Cash
                    </div>
                    <div class="col-sm-6">
                        {{ $totalSalesArr['cash'] }}
                    </div>
                    <div class="col-sm-6">
                        Credit
                    </div>
                    <div class="col-sm-6">
                        {{ $totalSalesArr['credit'] }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card card-chart">
            <div class="card-header collapsible" data-toggle="collapse" data-target="#totalPurchase">
                <h5 class="text-center">Total Purchase: <br><strong>{{ $totalPurchase }}</strong></h5>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card card-chart">
            <div class="card-header">
                <h5 class="card-category">( {{ $saleses->count() }} ) <em>Sales</em></h5>
                <h4 class="card-title">All Sales</h4>
                <div class="dropdown">
                    <button type="button"
                        class="btn btn-round btn-outline-default dropdown-toggle btn-simple btn-icon no-caret"
                        data-toggle="dropdown">
                        <i class="now-ui-icons ui-1_simple-add"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{{ route('sales.index') }}">Add Sales</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="chart-area">
                    <table class="datatable table">
                        <thead>
                            <th>S.N</th>
                            <th>Model No</th>
                            <th>Quantity</th>
                        </thead>
                        <tbody>
                            @foreach($saleses as $sales)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $sales->model_no }}</td>
                                <td>{{ $sales->quantity }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <i class="now-ui-icons arrows-1_refresh-69"></i> Just Updated
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card card-chart">
            <div class="card-header">
                <h5 class="card-category">( {{ $purchases->count() }} ) <em>Purchase</em></h5>
                <h4 class="card-title">All Purchases</h4>
                <div class="dropdown">
                    <button type="button"
                        class="btn btn-round btn-outline-default dropdown-toggle btn-simple btn-icon no-caret"
                        data-toggle="dropdown">
                        <i class="now-ui-icons ui-1_simple-add"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{{ route('purchase.create') }}">Add Purchase</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="chart-area">
                    <table class="datatable table">
                        <thead>
                            <th>S.N</th>
                            <th>Model No</th>
                            <th>Quantity</th>
                        </thead>
                        <tbody>
                            @foreach($purchases as $purchase)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $purchase->model_no }}</td>
                                <td>{{ $purchase->quantity }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <div class="stats">
                    Just Updated
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('.datatable').DataTable();
});
</script>
@endsection

resources/views/backend/footer.blade.php
<footer class="footer" >
  <div class=" container-fluid ">
   <div class="copyright" id="copyright">
    &copy; <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script>, Designed & Developed by <a href="#" target="_blank">Suman Mali</a>.
  </div>
</div>
</footer>

resources/views/backend/navbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
 <div class="container-fluid">
  <div class="navbar-wrapper">

   <div class="navbar-toggle">
    <button type="button" class="navbar-toggler">
     <span class="navbar-toggler-bar bar1"></span>
     <span class="navbar-toggler-bar bar2"></span>
     <span class="navbar-toggler-bar bar3"></span>
   </button>
 </div>

 <a class="navbar-brand" href="/home">Home</a>
</div>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-bar navbar-kebab"></span>
 <span class="navbar-toggler-bar navbar-kebab"></span>
 <span class="navbar-toggler-bar navbar-kebab"></span>
</button>

<div class="collapse navbar-collapse justify-content-end" id="navigation">


 
 <ul class="navbar-nav">
 
  <li class="nav-item">
    <a class="nav-link" href="{{ route('logout') }}"
    onclick="event.preventDefault();
    document.getElementById('logout-form').submit();">
    <i class="now-ui-icons users_single-02"></i>
    <p>
      <span class="d-lg-none d-md-block">Account</span>
    </p>
  </a>
  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
  </form>
</li>
</ul> 
</div>
</div>
</nav>

resources/views/backend/sidebar.blade.php
<div class="sidebar" data-color="blue">
    <div class="logo">
        <a href="/" class="simple-text logo-normal">
            Inventory Management
        </a>
    </div>
    <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
            <li class="active ">
                <a href="{{ route('lot.index') }}">
                    <i class="now-ui-icons design_app"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a href="{{ route('investor.index') }}">

                    <i class="now-ui-icons users_single-02"></i>

                    <p>Investors</p>
                </a>
            </li>
            <li>
                <a href="{{ route('expenses.index') }}">

                    <i class="now-ui-icons business_money-coins"></i>

                    <p>Expenses</p>
                </a>
            </li>
            <li>
                <a href="{{ route('purchase.index') }}">

                    <i class="now-ui-icons shopping_bag-16"></i>

                    <p>Purchase</p>
                </a>
            </li>
            <li>
                <a href="{{ route('sales.index') }}">

                    <i class="now-ui-icons arrows-1_share-66"></i>

                    <p>Sales</p>
                </a>
            </li>
            <li>
                <a href="{{ route('purchaseReturn.index') }}">

                    <i class="now-ui-icons arrows-1_cloud-upload-94"></i>

                    <p>Purchase Return</p>
                </a>
            </li>
            <li>
                <a href="{{ route('salesReturn.index') }}">

                    <i class="now-ui-icons arrows-1_cloud-download-93"></i>

                    <p>Sales Return</p>
                </a>
            </li>
            <li>
                <a href="/profitLoss">

                    <i class="now-ui-icons business_money-coins"></i>

                    <p>Profit / Loss</p>
                </a>
            </li>
            <li>
                <a href="/stocks">

                    <i class="now-ui-icons business_briefcase-24"></i>

                    <p>Stocks</p>
                </a>
            </li>
        </ul>
    </div>
</div>