routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@welcome');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('lot', 'LotController')->middleware('auth');
Route::resource('sales', 'SalesController')->middleware('auth');
Route::resource('purchase', 'PurchaseController')->middleware('auth');
Route::resource('purchaseReturn', 'PurchaseReturnController')->middleware('auth');
Route::resource('salesReturn', 'SalesReturnController')->middleware('auth');
Route::resource('investor', 'InvestorController')->middleware('auth');
Route::resource('expenses', 'ExpensesController')->middleware('auth');
Route::post('/vendors/store', 'VendorController@store');
Route::post('/customers/store', 'CustomerController@store');
Route::get('profitLoss', 'HomeController@profitLoss')->middleware('auth');
Route::get('stocks', 'HomeController@stock')->middleware('auth');
Route::fallback('PageController@error');

app/Investor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Investor extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name', 'amount', 'lot_id'
    ];
}

app/Http/Controllers/InvestorController.php
<?php

namespace App\Http\Controllers;

use App\Investor;
use Illuminate\Http\Request;

class InvestorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lot = session()->get('lot');
        $investors = Investor::where('lot_id', $lot->id)->get();
        return view('backend.investor.index', compact('investors', 'lot'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lot = session()->get('lot');
        return view('backend.investor.create', compact('lot'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Investor::create($request->all());
        return redirect('investor');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Investor  $investor
     * @return \Illuminate\Http\Response
     */
    public function show(Investor $investor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Investor  $investor
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lot = session()->get('lot');
        $investor = Investor::findOrFail($id);
        return view('backend.investor.edit', compact('investor', 'lot'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Investor  $investor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Investor::findOrFail($id)->update($request->all());
        return redirect('/investor')->with('success', 'Investor Details has been updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Investor  $investor
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Investor::findOrFail($id)->delete();
        return redirect('/investor')->with('success', 'Investor has been deleted successfully.');
    }
}

resources/views/backend/investor/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">Add New Investor Record</h4>
			</div>
			<div class="card-body">
				<form action="{{ route('investor.store') }}" method="POST" class="addForm" enctype="multipart/form-data">
					@csrf
					<input type="hidden" name="lot_id" value="{{ $lot->id }}">
					<div class="form-group col-md-4">
						<label for="name">Name</label>
						<input type="text" name="name" class="form-control" required placeholder="Name of Investor">
					</div>
					<div class="form-group col-md-4">
						<label for="amount">Amount</label>
						<input type="text" name="amount" class="form-control" required>
					</div>
					<button type="submit" class="btn btn-block col-md-4">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/investor/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">Edit Investor Record</h4>     
			</div>
			<div class="card-body">
				<form action="{{ route('investor.update', $investor->id) }}" method="POST" class="addForm" enctype="multipart/form-data">
					@csrf
					@method('PUT')
					<input type="hidden" name="lot_id" value="{{ $lot->id }}">
					<div class="form-group col-md-4">
						<label for="name">Name</label>
						<input type="text" name="name" class="form-control" required placeholder="Name of Investor" value="{{ $investor->name }}">
					</div>
					<div class="form-group col-md-4">
						<label for="amount">Amount</label>
						<input type="text" name="amount" class="form-control" required value="{{ $investor->amount }}">
					</div>
					<button type="submit" class="btn btn-block col-md-4">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/investor/index.blade.php
@extends('layouts.admin')

@section('styles')

@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    Investor Record
                </h4>
                <div>
                    <a href="{{ route('investor.create') }}" class="btn">
                        Add New Investor
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table datatable">
                        <thead class="text-primary">
                            <tr>
                                <th>
                                    S.N
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Amount
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($investors as $investor)
                            <tr>
                                <td>
                                    {{ $loop->iteration }}
                                </td>
                                <td>
                                    {{ $investor->name }}
                                </td>
                                <td>
                                    {{ $investor->amount }}
                                </td>
                                <td>
                                    <a href="{{ route('investor.edit', $investor->id) }}"
                                        class="btn btn-primary mb-1 btn-block">
                                        Edit
                                    </a>
                                    <form action="{{ route('investor.destroy', $investor->id) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-alert btn-block"
                                            onclick="promtAlert(event)">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
function promtAlert(evt) {
    var ans = confirm('Are you sure to delete?');
    if (!ans) {
        evt.preventDefault();
        evt.stopPropagation();
    }
}
</script>
@endsection