routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@welcome');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('lot', 'LotController')->middleware('auth');
Route::resource('sales', 'SalesController')->middleware('auth');
Route::resource('purchase', 'PurchaseController')->middleware('auth');
Route::resource('purchaseReturn', 'PurchaseReturnController')->middleware('auth');
Route::resource('salesReturn', 'SalesReturnController')->middleware('auth');
Route::resource('investor', 'InvestorController')->middleware('auth');
Route::resource('expenses', 'ExpensesController')->middleware('auth');
Route::post('/vendors/store', 'VendorController@store');
Route::post('/customers/store', 'CustomerController@store');
Route::get('profitLoss', 'HomeController@profitLoss')->middleware('auth');
Route::get('stocks', 'HomeController@stock')->middleware('auth');
Route::fallback('PageController@error');

app/Http/Controllers/ExpensesController.php
<?php

namespace App\Http\Controllers;

use App\Expenses;
use App\Purchase;
use App\Investor;

use Illuminate\Http\Request;

class ExpensesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lot = session()->get('lot');
        $expenses = Expenses::where('lot_id', $lot->id)->get();
        return view('backend.expenses.index', compact('lot', 'expenses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lot = session()->get('lot');
        $purchases = Purchase::where('lot_id', $lot->id)->get();
        
        $totalPurchase = 0;
        foreach($purchases as $purchase){
            $totalPurchase += $purchase->quantity * $purchase->price;
        }
        $amount = Investor::where('lot_id', $lot->id)->sum('amount');
        $canMakeExpenses = $amount - $totalPurchase;
        return view('backend.expenses.create', compact('lot', 'canMakeExpenses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Expenses::create($request->all());
        return redirect('expenses')->with('success', 'A new expenses record is added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function show(Expenses $expenses)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $expense = Expenses::findOrFail($id);
        $lot = session()->get('lot');
        return view('backend.expenses.edit', compact('expense', 'lot'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
        $expense = Expenses::findOrFail($id)->update($request->all());
        return redirect('expenses')->with('success', 'An expense record has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        Expenses::findOrFail($id)->delete();
        return redirect('expenses')->with('success', 'An expense record has been deleted!');
    }
}

resources/views/backend/expenses/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            @if($canMakeExpenses)
            <div class="card-header">
                <h4 class="card-title">Add New Expenses Record</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('expenses.store') }}" method="POST" class="addForm" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="lot_id" value="{{ $lot->id }}">
                    <div class="form-group col-md-4">
                        <label for="title">Title</label>
                        <input type="text" name="title" class="form-control" required placeholder="Title of Expenses">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="amount">Amount</label>
                        <input type="text" name="amount" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-block col-md-4">Submit</button>
                </form>
            </div>
            @else
            <div class="card-header">
                <h4 class="card-title">No Capital</h4>
            </div>
            @endif
        </div>
    </div>
</div>

@endsection

resources/views/backend/expenses/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">Edit Expenses Record</h4>     
			</div>
			<div class="card-body">
				<form action="{{ route('expenses.update', $expense->id) }}" method="POST" class="addForm" enctype="multipart/form-data">
					@csrf
					@method('PUT')
					<input type="hidden" name="lot_id" value="{{ $lot->id }}">
					<div class="form-group col-md-4">
						<label for="title">Title</label>
						<input type="text" name="title" class="form-control" value="{{ $expense->title}}" required placeholder="Title of Expenses">
					</div>
					<div class="form-group col-md-4">
						<label for="amount">Amount</label>
						<input type="text" name="amount" class="form-control" value="{{ $expense->amount}}" required>
					</div>
					<button type="submit" class="btn btn-block col-md-4">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/expenses/index.blade.php
@extends('layouts.admin')

@section('styles')

@endsection

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">
					Expenses Record
				</h4>
				<div>
					<a href="{{ route('expenses.create') }}" class="btn">
						Add New Expenses
					</a>
				</div>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table datatable">
						<thead class="text-primary">                   
							<tr>
								<th>    
									S.N  
								</th>
								<th>
									Title
								</th>
								<th>
									Amount
								</th>
								<th>
									Action
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach($expenses as $expense)
							<tr>
								<td>    
									{{ $loop->iteration }}
								</td>
								<td>
									{{ $expense->title }}
								</td>
								<td>
									{{ $expense->amount }}
								</td>
								<td>
									<a href="{{ route('expenses.edit', $expense->id) }}" class="btn btn-primary btn-block">
										Edit
									</a>
									<form action="{{ route('expenses.destroy', $expense->id) }}" method="POST">
										@csrf
										@method('delete')
										<button class="btn btn-alert btn-block" onclick="promtAlert(event)">Delete</button>
									</form>
								</td>
							</tr>
							@endforeach  
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('scripts')
<script>
	function promtAlert(evt){
		var ans = confirm('Are you sure to delete?');
		if(!ans){
			evt.preventDefault();
			evt.stopPropagation();
		}
	}
</script>
@endsection